[project]
name = "arxiv-semantic-search-mcp"
version = "0.1.0"
description = "Semantic search for arXiv papers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.5",
]
